# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'EnglishGo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for EnglishGo
pod 'SnapKit', '~> 3.2.0'
pod 'Kingfisher', '~> 3.0'
pod 'MBProgressHUD', '~> 1.0.0'
pod 'Alamofire', '~> 4.4'
pod 'lottie-ios', '~> 1.0'
pod 'pop', '~> 1.0'
pod 'LTMorphingLabel'
pod 'FaveButton', '~> 2.0.3'
pod 'NVActivityIndicatorView'
pod 'CNPPopupController'
  target 'EnglishGo-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'EnglishGoTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
