/**
 * Created by vjtc0n on 6/14/17.
 */
export const images = {
  '1'  : {
    1: require('../data/airplane/1.jpg'),
    2: require('../data/airplane/2.jpg'),
    3: require('../data/airplane/3.jpg'),
    4: require('../data/airplane/4.jpg'),
    5: require('../data/airplane/5.jpg'),
    6: require('../data/airplane/6.jpg'),
    7: require('../data/airplane/7.jpg'),
    8: require('../data/airplane/8.jpg'),
    9: require('../data/airplane/9.jpg'),
    10: require('../data/airplane/10.jpg')
  }
  ,
  '2'  : {
    1: require('../data/boat/1.jpg'),
    2: require('../data/boat/2.jpg'),
    3: require('../data/boat/3.jpg'),
    4: require('../data/boat/4.jpg'),
    5: require('../data/boat/5.jpg'),
    6: require('../data/boat/6.jpg'),
    7: require('../data/boat/7.jpg'),
    8: require('../data/boat/8.jpg'),
    9: require('../data/boat/9.jpg'),
    10: require('../data/boat/10.jpg')
  },
  '3'  : {
    1: require('../data/bicycle/1.jpg'),
    2: require('../data/bicycle/2.jpg'),
    3: require('../data/bicycle/3.jpg'),
    4: require('../data/bicycle/4.jpg'),
    5: require('../data/bicycle/5.jpg'),
    6: require('../data/bicycle/6.jpg'),
    7: require('../data/bicycle/7.jpg'),
    8: require('../data/bicycle/8.jpg'),
    9: require('../data/bicycle/9.jpg'),
    10: require('../data/bicycle/10.jpg')
  },
  '4'  : {
    1: require('../data/bear/1.jpg'),
    2: require('../data/bear/2.jpg'),
    3: require('../data/bear/3.jpg'),
    4: require('../data/bear/4.jpg'),
    5: require('../data/bear/5.jpg'),
    6: require('../data/bear/6.jpg'),
    7: require('../data/bear/7.jpg'),
    8: require('../data/bear/8.jpg'),
    9: require('../data/bear/9.jpg'),
    10: require('../data/bear/10.jpg')
  },
  '5'  : {
    1: require('../data/bird/1.jpg'),
    2: require('../data/bird/2.jpg'),
    3: require('../data/bird/3.jpg'),
    4: require('../data/bird/4.jpg'),
    5: require('../data/bird/5.jpg'),
    6: require('../data/bird/6.jpg'),
    7: require('../data/bird/7.jpg'),
    8: require('../data/bird/8.jpg'),
    9: require('../data/bird/9.jpg'),
    10: require('../data/bird/10.jpg')
  },
  '6'  : {
    1: require('../data/dog/1.jpg'),
    2: require('../data/dog/2.jpg'),
    3: require('../data/dog/3.jpg'),
    4: require('../data/dog/4.jpg'),
    5: require('../data/dog/5.jpg'),
    6: require('../data/dog/6.jpg'),
    7: require('../data/dog/7.jpg'),
    8: require('../data/dog/8.jpg'),
    9: require('../data/dog/9.jpg'),
    10: require('../data/dog/10.jpg')
  },
  '7'  : {
    1: require('../data/bus/1.jpg'),
    2: require('../data/bus/2.jpg'),
    3: require('../data/bus/3.jpg'),
    4: require('../data/bus/4.jpg'),
    5: require('../data/bus/5.jpg'),
    6: require('../data/bus/6.jpg'),
    7: require('../data/bus/7.jpg'),
    8: require('../data/bus/8.jpg'),
    9: require('../data/bus/9.jpg'),
    10: require('../data/bus/10.jpg')
  },
  '8'  : {
    1: require('../data/car/1.jpg'),
    2: require('../data/car/2.jpg'),
    3: require('../data/car/3.jpg'),
    4: require('../data/car/4.jpg'),
    5: require('../data/car/5.jpg'),
    6: require('../data/car/6.jpg'),
    7: require('../data/car/7.jpg'),
    8: require('../data/car/8.jpg'),
    9: require('../data/car/9.jpg'),
    10: require('../data/car/10.jpg')
  },
  '9'  : {
    1: require('../data/motorcycle/1.jpg'),
    2: require('../data/motorcycle/2.jpg'),
    3: require('../data/motorcycle/3.jpg'),
    4: require('../data/motorcycle/4.jpg'),
    5: require('../data/motorcycle/5.jpg'),
    6: require('../data/motorcycle/6.jpg'),
    7: require('../data/motorcycle/7.jpg'),
    8: require('../data/motorcycle/8.jpg'),
    9: require('../data/motorcycle/9.jpg'),
    10: require('../data/motorcycle/10.jpg')
  },
  '10'  : {
    1: require('../data/cat/1.jpg'),
    2: require('../data/cat/2.jpg'),
    3: require('../data/cat/3.jpg'),
    4: require('../data/cat/4.jpg'),
    5: require('../data/cat/5.jpg'),
    6: require('../data/cat/6.jpg'),
    7: require('../data/cat/7.jpg'),
    8: require('../data/cat/8.jpg'),
    9: require('../data/cat/9.jpg'),
    10: require('../data/cat/10.jpg')
  },
  '11'  : {
    1: require('../data/sheep/1.jpg'),
    2: require('../data/sheep/2.jpg'),
    3: require('../data/sheep/3.jpg'),
    4: require('../data/sheep/4.jpg'),
    5: require('../data/sheep/5.jpg'),
    6: require('../data/sheep/6.jpg'),
    7: require('../data/sheep/7.jpg'),
    8: require('../data/sheep/8.jpg'),
    9: require('../data/sheep/9.jpg'),
    10: require('../data/sheep/10.jpg')
  },
  '12'  : {
    1: require('../data/zebra/1.jpg'),
    2: require('../data/zebra/2.jpg'),
    3: require('../data/zebra/3.jpg'),
    4: require('../data/zebra/4.jpg'),
    5: require('../data/zebra/5.jpg'),
    6: require('../data/zebra/6.jpg'),
    7: require('../data/zebra/7.jpg'),
    8: require('../data/zebra/8.jpg'),
    9: require('../data/zebra/9.jpg'),
    10: require('../data/zebra/10.jpg')
  },
  '13'  : {
    1: require('../data/boat/1.jpg'),
    2: require('../data/boat/2.jpg'),
    3: require('../data/boat/3.jpg'),
    4: require('../data/boat/4.jpg'),
    5: require('../data/boat/5.jpg'),
    6: require('../data/boat/6.jpg'),
    7: require('../data/boat/7.jpg'),
    8: require('../data/boat/8.jpg'),
    9: require('../data/boat/9.jpg'),
    10: require('../data/boat/10.jpg')
  },
  '14'  : {
    1: require('../data/bicycle/1.jpg'),
    2: require('../data/bicycle/2.jpg'),
    3: require('../data/bicycle/3.jpg'),
    4: require('../data/bicycle/4.jpg'),
    5: require('../data/bicycle/5.jpg'),
    6: require('../data/bicycle/6.jpg'),
    7: require('../data/bicycle/7.jpg'),
    8: require('../data/bicycle/8.jpg'),
    9: require('../data/bicycle/9.jpg'),
    10: require('../data/bicycle/10.jpg')
  },
  '15'  : {
    1: require('../data/bus/1.jpg'),
    2: require('../data/bus/2.jpg'),
    3: require('../data/bus/3.jpg'),
    4: require('../data/bus/4.jpg'),
    5: require('../data/bus/5.jpg'),
    6: require('../data/bus/6.jpg'),
    7: require('../data/bus/7.jpg'),
    8: require('../data/bus/8.jpg'),
    9: require('../data/bus/9.jpg'),
    10: require('../data/bus/10.jpg')
  },
  '16'  : {
    1: require('../data/elephant/1.jpg'),
    2: require('../data/elephant/2.jpg'),
    3: require('../data/elephant/3.jpg'),
    4: require('../data/elephant/4.jpg'),
    5: require('../data/elephant/5.jpg'),
    6: require('../data/elephant/6.jpg'),
    7: require('../data/elephant/7.jpg'),
    8: require('../data/elephant/8.jpg'),
    9: require('../data/elephant/9.jpg'),
    10: require('../data/elephant/10.jpg')
  },
  '17'  : {
    1: require('../data/giraffe/1.jpg'),
    2: require('../data/giraffe/2.jpg'),
    3: require('../data/giraffe/3.jpg'),
    4: require('../data/giraffe/4.jpg'),
    5: require('../data/giraffe/5.jpg'),
    6: require('../data/giraffe/6.jpg'),
    7: require('../data/giraffe/7.jpg'),
    8: require('../data/giraffe/8.jpg'),
    9: require('../data/giraffe/9.jpg'),
    10: require('../data/giraffe/10.jpg')
  },
  '18'  : {
    1: require('../data/horse/1.jpg'),
    2: require('../data/horse/2.jpg'),
    3: require('../data/horse/3.jpg'),
    4: require('../data/horse/4.jpg'),
    5: require('../data/horse/5.jpg'),
    6: require('../data/horse/6.jpg'),
    7: require('../data/horse/7.jpg'),
    8: require('../data/horse/8.jpg'),
    9: require('../data/horse/9.jpg'),
    10: require('../data/horse/10.jpg')
  },
  '19'  : {
    1: require('../data/traffic_light/1.jpg'),
    2: require('../data/traffic_light/2.jpg'),
    3: require('../data/traffic_light/3.jpg'),
    4: require('../data/traffic_light/4.jpg'),
    5: require('../data/traffic_light/5.jpg'),
    6: require('../data/traffic_light/6.jpg'),
    7: require('../data/traffic_light/7.jpg'),
    8: require('../data/traffic_light/8.jpg'),
    9: require('../data/traffic_light/9.jpg'),
    10: require('../data/traffic_light/10.jpg')
  },
  '20'  : {
    1: require('../data/stop_sign/1.jpg'),
    2: require('../data/stop_sign/2.jpg'),
    3: require('../data/stop_sign/3.jpg'),
    4: require('../data/stop_sign/4.jpg'),
    5: require('../data/stop_sign/5.jpg'),
    6: require('../data/stop_sign/6.jpg'),
    7: require('../data/stop_sign/7.jpg'),
    8: require('../data/stop_sign/8.jpg'),
    9: require('../data/stop_sign/9.jpg'),
    10: require('../data/stop_sign/10.jpg')
  },
  '21'  : {
    1: require('../data/parking_meter/1.jpg'),
    2: require('../data/parking_meter/2.jpg'),
    3: require('../data/parking_meter/3.jpg'),
    4: require('../data/parking_meter/4.jpg'),
    5: require('../data/parking_meter/5.jpg'),
    6: require('../data/parking_meter/6.jpg'),
    7: require('../data/parking_meter/7.jpg'),
    8: require('../data/parking_meter/8.jpg'),
    9: require('../data/parking_meter/9.jpg'),
    10: require('../data/parking_meter/10.jpg')
  },
  '22'  : {
    1: require('../data/bed/1.jpg'),
    2: require('../data/bed/2.jpg'),
    3: require('../data/bed/3.jpg'),
    4: require('../data/bed/4.jpg'),
    5: require('../data/bed/5.jpg'),
    6: require('../data/bed/6.jpg'),
    7: require('../data/bed/7.jpg'),
    8: require('../data/bed/8.jpg'),
    9: require('../data/bed/9.jpg'),
    10: require('../data/bed/10.jpg')
  },
  '23'  : {
    1: require('../data/sink/1.jpg'),
    2: require('../data/sink/2.jpg'),
    3: require('../data/sink/3.jpg'),
    4: require('../data/sink/4.jpg'),
    5: require('../data/sink/5.jpg'),
    6: require('../data/sink/6.jpg'),
    7: require('../data/sink/7.jpg'),
    8: require('../data/sink/8.jpg'),
    9: require('../data/sink/9.jpg'),
    10: require('../data/sink/10.jpg')
  },
  '24'  : {
    1: require('../data/potted plant/1.jpg'),
    2: require('../data/potted plant/2.jpg'),
    3: require('../data/potted plant/3.jpg'),
    4: require('../data/potted plant/4.jpg'),
    5: require('../data/potted plant/5.jpg'),
    6: require('../data/potted plant/6.jpg'),
    7: require('../data/potted plant/7.jpg'),
    8: require('../data/potted plant/8.jpg'),
    9: require('../data/potted plant/9.jpg'),
    10: require('../data/potted plant/10.jpg')
  },
  '25'  : {
    1: require('../data/chair/1.jpg'),
    2: require('../data/chair/2.jpg'),
    3: require('../data/chair/3.jpg'),
    4: require('../data/chair/4.jpg'),
    5: require('../data/chair/5.jpg'),
    6: require('../data/chair/6.jpg'),
    7: require('../data/chair/7.jpg'),
    8: require('../data/chair/8.jpg'),
    9: require('../data/chair/9.jpg'),
    10: require('../data/chair/10.jpg')
  },
  '26'  : {
    1: require('../data/couch/1.jpg'),
    2: require('../data/couch/2.jpg'),
    3: require('../data/couch/3.jpg'),
    4: require('../data/couch/4.jpg'),
    5: require('../data/couch/5.jpg'),
    6: require('../data/couch/6.jpg'),
    7: require('../data/couch/7.jpg'),
    8: require('../data/couch/8.jpg'),
    9: require('../data/couch/9.jpg'),
    10: require('../data/couch/10.jpg')
  },
  '27'  : {
    1: require('../data/bench/1.jpg'),
    2: require('../data/bench/2.jpg'),
    3: require('../data/bench/3.jpg'),
    4: require('../data/bench/4.jpg'),
    5: require('../data/bench/5.jpg'),
    6: require('../data/bench/6.jpg'),
    7: require('../data/bench/7.jpg'),
    8: require('../data/bench/8.jpg'),
    9: require('../data/bench/9.jpg'),
    10: require('../data/bench/10.jpg')
  },
  '28'  : {
    1: require('../data/apple/1.jpg'),
    2: require('../data/apple/2.jpg'),
    3: require('../data/apple/3.jpg'),
    4: require('../data/apple/4.jpg'),
    5: require('../data/apple/5.jpg'),
    6: require('../data/apple/6.jpg'),
    7: require('../data/apple/7.jpg'),
    8: require('../data/apple/8.jpg'),
    9: require('../data/apple/9.jpg'),
    10: require('../data/apple/10.jpg')
  },
  '29'  : {
    1: require('../data/orange/1.jpg'),
    2: require('../data/orange/2.jpg'),
    3: require('../data/orange/3.jpg'),
    4: require('../data/orange/4.jpg'),
    5: require('../data/orange/5.jpg'),
    6: require('../data/orange/6.jpg'),
    7: require('../data/orange/7.jpg'),
    8: require('../data/orange/8.jpg'),
    9: require('../data/orange/9.jpg'),
    10: require('../data/orange/10.jpg')
  },
  '30'  : {
    1: require('../data/banana/1.jpg'),
    2: require('../data/banana/2.jpg'),
    3: require('../data/banana/3.jpg'),
    4: require('../data/banana/4.jpg'),
    5: require('../data/banana/5.jpg'),
    6: require('../data/banana/6.jpg'),
    7: require('../data/banana/7.jpg'),
    8: require('../data/banana/8.jpg'),
    9: require('../data/banana/9.jpg'),
    10: require('../data/banana/10.jpg')
  }
}